include: package:flutter_lints/flutter.yaml

analyzer:
  # exclude:
  #   - "**/**.g.dart"
  # errors:
  #   deprecated_member_use_from_same_package: ignore
  #   deprecated_member_use: ignore # Add this line to ignore deprecated member use errors

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: false
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: false
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_renaming_method_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: false
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: false
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    eol_at_end_of_file: false
    exhaustive_cases: true
    file_names: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: false
    lines_longer_than_80_chars: false
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    null_closures: false
    omit_local_variable_types: true
    one_member_abstracts: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    type_init_formals: true
    type_annotate_public_apis: true
    tighten_type_of_initializing_formals: true
    super_goes_last: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: false
    sort_child_properties_last: true
    slash_for_doc_comments: true
    sized_box_shrink_expand: true
    sized_box_for_whitespace: true
    require_trailing_commas: true
    prefer_spread_collections: true
    prefer_single_quotes: true
    prefer_null_aware_operators: true
    prefer_null_aware_method_calls: true
    prefer_mixin: true
    prefer_iterable_whereType: true
    prefer_is_not_operator: true
    prefer_is_not_empty: true
    prefer_is_empty: true
    prefer_interpolation_to_compose_strings: true
    prefer_if_null_operators: true
    prefer_generic_function_type_aliases: true
    prefer_function_declarations_over_variables: true
    prefer_foreach: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_expression_function_bodies: false
    prefer_equal_for_default_values: true
    prefer_constructors_over_static_methods: true
    prefer_const_literals_to_create_immutables: true
    use_to_and_as_if_applicable: true
    use_test_throws_matchers: true
    use_super_parameters: true
    use_setters_to_change_properties: true
    use_rethrow_when_possible: true
    use_named_constants: true
    use_full_hex_values_for_flutter_colors: true
    use_decorated_box: true
    use_colored_box: true
    unnecessary_string_interpolations: true
    unnecessary_new: true
    unnecessary_lambdas: true
    unnecessary_breaks: true
    unnecessary_brace_in_string_interps: true
    unawaited_futures: true
    deprecated_member_use_from_same_package: false
