name: tempo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  pitch_detector_dart: ^0.0.7
  flutter_audio_capture: ^1.1.12
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.5
  json_annotation: ^4.11.0
  audio_streamer: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/frequencies/

flutter_gen:
  output: lib/gen/
